export const BASE_URL = "http://127.0.0.1:8000";

//USERS
export const POST_USERS_LOGIN_SUCCESS = "POST_USERS_LOGIN_SUCCESS";
export const POST_USERS_LOGIN_FAILURE = "POST_USERS_LOGIN_FAILURE";
export const POST_USERS_REGISTER_SUCCESS = "POST_USERS_REGISTER_SUCCESS";
export const POST_USERS_REGISTER_FAILURE = "POST_USERS_REGISTER_FAILURE";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"

//ENQUIRIES
export const POST_ENQUIRIES_SUCCESS = "POST_ENQUIRIES_SUCCESS";
export const POST_ENQUIRIES_FAILURE = "POST_ENQUIRIES_FAILURE";