export const BASE_URL = "http://127.0.0.1:8000";

//USERS
export const POST_USERS_LOGIN_SUCCESS = "POST_USERS_LOGIN_SUCCESS";
export const POST_USERS_LOGIN_FAILURE = "POST_USERS_LOGIN_FAILURE";
export const POST_USERS_REGISTER_SUCCESS = "POST_USERS_REGISTER_SUCCESS";
export const POST_USERS_REGISTER_FAILURE = "POST_USERS_REGISTER_FAILURE";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_COUNTRIES_SUCCESS = "GET_USERS_SUCCESS";
export const GET_COUNTRIES_FAILURE = "GET_COUNTRIES_FAILURE";

//ENQUIRIES
export const POST_ENQUIRIES_SUCCESS = "POST_ENQUIRIES_SUCCESS";
export const POST_ENQUIRIES_FAILURE = "POST_ENQUIRIES_FAILURE";
export const GET_ENQUIRIES_SUCCESS = "GET_ENQUIRIES_SUCCESS";
export const GET_ENQUIRIES_FAILURE = "GET_ENQUIRIES_FAILURE";

//MENU
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILURE = "GET_MENU_FAILURE";