export const BASE_URL = "http://127.0.0.1:8000";

//USERS
export const POST_USERS_LOGIN_SUCCESS = "POST_USERS_LOGIN_SUCCESS";
export const POST_USERS_LOGIN_FAILURE = "POST_USERS_LOGIN_FAILURE";
export const POST_USERS_REGISTER_SUCCESS = "POST_USERS_REGISTER_SUCCESS";
export const POST_USERS_REGISTER_FAILURE = "POST_USERS_REGISTER_FAILURE";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_COUNTRIES_SUCCESS = "GET_USERS_SUCCESS";
export const GET_COUNTRIES_FAILURE = "GET_COUNTRIES_FAILURE";

//ENQUIRIES
export const POST_ENQUIRIES_SUCCESS = "POST_ENQUIRIES_SUCCESS";
export const POST_ENQUIRIES_FAILURE = "POST_ENQUIRIES_FAILURE";
export const GET_ENQUIRIES_SUCCESS = "GET_ENQUIRIES_SUCCESS";
export const GET_ENQUIRIES_FAILURE = "GET_ENQUIRIES_FAILURE";

//DESTINATION
export const POST_DESTINATION_SUCCESS = "POST_DESTINATION_SUCCESS";
export const POST_DESTINATION_FAILURE = "POST_DESTINATION_FAILURE";
export const GET_DESTINATION_SUCCESS = "GET_DESTINATION_SUCCESS";
export const GET_DESTINATION_FAILURE = "GET_DESTINATION_FAILURE";

//MENU
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILURE = "GET_MENU_FAILURE";

//TOURS
export const POST_TOUR_FAILURE = "POST_TOUR_FAILURE";
export const GET_TOUR_SUCCESS = "GET_TOUR_SUCCESS"
export const POST_TOUR_SUCCESS = "POST_TOUR_SUCCESS";
export const UPDATE_SHARE_YOUR_TOUR = "UPDATE_SHARE_YOUR_TOUR";
export const UPDATE_SHARE_YOUR_TOUR_DETAILS = "UPDATE_SHARE_YOUR_TOUR_DETAILS";
export const UPDATE_SHARE_YOUR_TOUR_ITINERARY = "UPDATE_SHARE_YOUR_TOUR_ITINERARY";
export const UPDATE_SHARE_YOUR_TOUR_GALLERY = "UPDATE_SHARE_YOUR_TOUR_GALLERY";